### ISSUE TITLE
JSONDecodeError while listing samples with biomes and metadata

### ISSUE THREAD

**Issue by evilvenom** [EBI-Metagenomics/emgapi-examples#2]
I am experiencing this decode error while extracting a list of samples with biomes and metadata ([reference](https://render.githubusercontent.com/view/ipynb?color_mode=auto&commit=44d3ae57fdd5ba35a243659e582a8c513dbcd85f&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f4542492d4d65746167656e6f6d6963732f6578616d706c65732f343464336165353766646435626133356132343336353965353832613863353133646263643835662f6d676e6966792f7372632f6e6f7465626f6f6b732f616e73776572732f414e535745525f6578616d706c65732e6970796e62&nwo=EBI-Metagenomics%2Fexamples&path=mgnify%2Fsrc%2Fnotebooks%2Fanswers%2FANSWER_examples.ipynb&repository_id=105248166&repository_type=Repository#List-samples-with-biomes-and-metadata-for-the-given-study)) as well as while doing the same with metagenomic marine samples from a certain temperature range ([reference](https://render.githubusercontent.com/view/ipynb?color_mode=auto&commit=44d3ae57fdd5ba35a243659e582a8c513dbcd85f&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f4542492d4d65746167656e6f6d6963732f6578616d706c65732f343464336165353766646435626133356132343336353965353832613863353133646263643835662f6d676e6966792f7372632f6e6f7465626f6f6b732f616e73776572732f414e535745525f6578616d706c65732e6970796e62&nwo=EBI-Metagenomics%2Fexamples&path=mgnify%2Fsrc%2Fnotebooks%2Fanswers%2FANSWER_examples.ipynb&repository_id=105248166&repository_type=Repository#List-samples-with-biomes-and-metadata-for-the-given-study))

Can you please help me with the same?

**Comment by SandyRogers** [comment]
@evilvenom thanks for opening the issue. There is a bug in the MGnify API currently, which we are working on, affecting the use of some `include` filters. Sorry about this.

If you remove the `'include': 'biome'` from the `Filter` parameters, the example should work for now (and the biome will still be available).

So, change the code to:
```python
with Session(API_BASE) as s:
    params = {
        'study_accession': 'ERP001736',
        # 'include': 'biome',
        'page_size': 100,
    }
    f = Filter(urlencode(params))
```

**Comment by evilvenom** [comment]
> @evilvenom thanks for opening the issue. There is a bug in the MGnify API currently, which we are working on, affecting the use of some `include` filters. Sorry about this.
> 
> If you remove the `'include': 'biome'` from the `Filter` parameters, the example should work for now (and the biome will still be available).
> 
> So, change the code to:
> 
> ```python
> with Session(API_BASE) as s:
>     params = {
>         'study_accession': 'ERP001736',
>         # 'include': 'biome',
>         'page_size': 100,
>     }
>     f = Filter(urlencode(params))
> ```

Thanks a lot. 
Really appreciate the quick reply.

Stay safe and stay well!

**Comment by SandyRogers** [comment]
You're very welcome!
